# Generated by Django 3.2.8 on 2021-11-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
    ]
